"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os   
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$7*pmfz+xi3r*5c(ol18lou&7e=o%=6wr0r39+g%z)wiiefy=l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites', # 必須添加
    'allauth',
    'allauth.account',
    'allauth.socialaccount', # 如果需要社群登入才加
    'allauth.socialaccount.providers.google',
    'users',
]

SITE_ID = 1

# 設置驗證後端
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 新增下面這一行
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 將語言代碼改為繁體中文
LANGUAGE_CODE = 'zh-Hant'

# 時區建議也順便改成台灣
TIME_ZONE = 'Asia/Taipei'

USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 登入與導向設定
LOGIN_REDIRECT_URL = '/dashboard/' # 登入後跳轉到首頁
LOGOUT_REDIRECT_URL = '/' # 登出後跳轉到首頁    
ACCOUNT_LOGOUT_REDIRECT_URL = '/accounts/login/' # 登出後跳轉到首頁
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- 舊的設定 (請註解掉或刪除) ---
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# ACCOUNT_EMAIL_REQUIRED = True

# --- 新的設定 (符合新版規範) ---

# 1. 決定使用者可以用什麼登入 (帳號、Email 或兩者皆可)
ACCOUNT_LOGIN_METHODS = {'username', 'email'}

# 2. 決定註冊頁面顯示哪些欄位，以及是否必填
# '*' 代表必填，若不加則為選填
ACCOUNT_SIGNUP_FIELDS = [
    'email*',       # Email 必填
    'username*',    # 使用者名稱 必填
    'password1*',   # 密碼 必填
    'password2*'    # 確認密碼 必填
]

# 3. 關於密碼 (新版通常建議將 password 欄位也顯式列出以確保完整性)
# 注意：password1* 和 password2* 是為了確保兩次輸入一致

# 註冊後是否需要驗證 Email 才能登入？
# 可選值: 'mandatory' (強制), 'optional' (選填), 'none' (不驗證)
ACCOUNT_EMAIL_VERIFICATION = 'none' # 建議開發初期先設為 none，方便測試